name: build react app
on:
  push:
    branches:
      - 'main'
      - 'releases/**'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: install dependencies
        run: npm ci
      - name: run tests
        run: npm run test
  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC_HOST }}
          username: ${{ secrets.EC_USERNAME }}
          key: ${{ secrets.EC_PRIVATE_KEY }}
          port: 22
          script: |
            if [ "$(docker ps -aq -f name=react_app)" ]; then
             sudo docker stop react_app
             sudo docker rm react_app
             sudo docker rmi ${{ secrets.DOCKER_USERNAME }}/todo_app:latest
            fi
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/todo_app:latest
            sudo docker run --name=react_app -d -p 8000:80 ${{ secrets.DOCKER_USERNAME }}/todo_app:latest
